wandb_version: 1

data_dir:
  desc: null
  value: /workspace/datasets/akane/imagenette2
dataset:
  desc: null
  value: imagenette2
train_split:
  desc: null
  value: train
val_split:
  desc: null
  value: validation
dataset_download:
  desc: null
  value: false
class_map:
  desc: null
  value: ''
model:
  desc: null
  value: wintome_dinat_s_tiny
pretrained:
  desc: null
  value: false
initial_checkpoint:
  desc: null
  value: ''
resume:
  desc: null
  value: ''
no_resume_opt:
  desc: null
  value: false
num_classes:
  desc: null
  value: 10
gp:
  desc: null
  value: null
img_size:
  desc: null
  value: 224
input_size:
  desc: null
  value: null
crop_pct:
  desc: null
  value: 0.875
mean:
  desc: null
  value: null
std:
  desc: null
  value: null
interpolation:
  desc: null
  value: ''
batch_size:
  desc: null
  value: 128
validation_batch_size:
  desc: null
  value: null
disable_eval:
  desc: null
  value: false
opt:
  desc: null
  value: adamw
opt_eps:
  desc: null
  value: 1.0e-08
opt_betas:
  desc: null
  value:
  - 0.9
  - 0.999
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 5.0e-06
clip_grad:
  desc: null
  value: 5.0
clip_mode:
  desc: null
  value: norm
sched:
  desc: null
  value: cosine
sched_epochwise:
  desc: null
  value: false
lr:
  desc: null
  value: 1.0e-05
lr_noise:
  desc: null
  value: null
lr_noise_pct:
  desc: null
  value: 0.67
lr_noise_std:
  desc: null
  value: 1.0
lr_cycle_mul:
  desc: null
  value: 1.0
lr_cycle_decay:
  desc: null
  value: 1.0
lr_cycle_limit:
  desc: null
  value: 1
lr_k_decay:
  desc: null
  value: 1.0
warmup_lr:
  desc: null
  value: 1.0e-06
min_lr:
  desc: null
  value: 5.0e-06
epochs:
  desc: null
  value: 300
epoch_repeats:
  desc: null
  value: 0.0
start_epoch:
  desc: null
  value: null
decay_epochs:
  desc: null
  value: 100
warmup_epochs:
  desc: null
  value: 20
cooldown_epochs:
  desc: null
  value: 10
patience_epochs:
  desc: null
  value: 10
decay_rate:
  desc: null
  value: 0.1
no_aug:
  desc: null
  value: false
scale:
  desc: null
  value:
  - 0.08
  - 1.0
ratio:
  desc: null
  value:
  - 0.75
  - 1.3333333333333333
hflip:
  desc: null
  value: 0.5
vflip:
  desc: null
  value: 0.0
color_jitter:
  desc: null
  value: 0.4
aa:
  desc: null
  value: rand-m9-mstd0.5-inc1
aug_repeats:
  desc: null
  value: 0
aug_splits:
  desc: null
  value: 0
jsd_loss:
  desc: null
  value: false
bce_loss:
  desc: null
  value: false
bce_target_thresh:
  desc: null
  value: null
reprob:
  desc: null
  value: 0.25
remode:
  desc: null
  value: pixel
recount:
  desc: null
  value: 1
resplit:
  desc: null
  value: false
mixup:
  desc: null
  value: 0.8
cutmix:
  desc: null
  value: 1.0
cutmix_minmax:
  desc: null
  value: null
mixup_prob:
  desc: null
  value: 1.0
mixup_switch_prob:
  desc: null
  value: 0.5
mixup_mode:
  desc: null
  value: batch
mixup_off_epoch:
  desc: null
  value: 0
smoothing:
  desc: null
  value: 0.1
train_interpolation:
  desc: null
  value: random
drop:
  desc: null
  value: 0.0
drop_connect:
  desc: null
  value: null
drop_block:
  desc: null
  value: null
bn_tf:
  desc: null
  value: false
bn_momentum:
  desc: null
  value: null
bn_eps:
  desc: null
  value: null
sync_bn:
  desc: null
  value: false
dist_bn:
  desc: null
  value: reduce
split_bn:
  desc: null
  value: false
model_ema:
  desc: null
  value: false
model_ema_force_cpu:
  desc: null
  value: false
model_ema_decay:
  desc: null
  value: 0.9998
seed:
  desc: null
  value: 42
worker_seeding:
  desc: null
  value: all
log_interval:
  desc: null
  value: 50
recovery_interval:
  desc: null
  value: 0
checkpoint_hist:
  desc: null
  value: 4
workers:
  desc: null
  value: 8
save_images:
  desc: null
  value: false
amp:
  desc: null
  value: true
apex_amp:
  desc: null
  value: false
native_amp:
  desc: null
  value: true
no_ddp_bb:
  desc: null
  value: false
channels_last:
  desc: null
  value: false
pin_mem:
  desc: null
  value: false
no_prefetcher:
  desc: null
  value: false
output:
  desc: null
  value: /workspace/akane/runs
experiment:
  desc: null
  value: 20231004-213609-wintome_dinat_s_tiny-224
project:
  desc: null
  value: wintome-dinat-s-imagenette
eval_metric:
  desc: null
  value: top1
tta:
  desc: null
  value: 0
local_rank:
  desc: null
  value: 0
use_multi_epochs_loader:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
log_wandb:
  desc: null
  value: true
world_size:
  desc: null
  value: 2
dist_url:
  desc: null
  value: env://
prefetcher:
  desc: null
  value: true
distributed:
  desc: null
  value: true
device:
  desc: null
  value: cuda:0
rank:
  desc: null
  value: 0
gmacs:
  desc: null
  value: 4.102429584
mparams:
  desc: null
  value: 27.340708
_wandb:
  desc: null
  value:
    code_path: code/classification/train.py
    python_version: 3.11.5
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696480571.709731
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.11.5
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
